In [1]:
import laspy
import open3d as o3d
import numpy as np

In [2]:
las = laspy.read("data/lidar.las")
las

<LasData(1.2, point fmt: <PointFormat(1, 0 bytes of extra dims)>, 46150 points, 4 vlrs)>

In [3]:
list(las.point_format.dimension_names)


['X',
 'Y',
 'Z',
 'intensity',
 'return_number',
 'number_of_returns',
 'scan_direction_flag',
 'edge_of_flight_line',
 'classification',
 'synthetic',
 'key_point',
 'withheld',
 'scan_angle_rank',
 'user_data',
 'point_source_id',
 'gps_time']

In [4]:
las.X

array([65948887, 65948947, 65949008, ..., 65953275, 65953341, 65953329],
      dtype=int32)

In [5]:
las.intensity

array([14,  9, 28, ..., 19, 36, 25], dtype=uint16)

In [6]:
las.gps_time

array([ 82850.15856803,  82850.15857803,  82850.15858803, ...,
       146773.41777289, 146773.41778288, 146773.41910291])

In [7]:
set(list(las.classification))

{1, 2}

# Creating, Filtering, and Writing Point Cloud Data


In [8]:
point_data = np.stack([las.X, las.Y, las.Z], axis=0).transpose((1, 0))
point_data

array([[ 65948887, 437130910,     56975],
       [ 65948947, 437130938,     56985],
       [ 65949008, 437130966,     56995],
       ...,
       [ 65953275, 437125842,     61213],
       [ 65953341, 437125868,     61153],
       [ 65953329, 437125854,     61172]], dtype=int32)

In [9]:
ground = laspy.create(point_format=las.header.point_format, file_version=las.header.version)
ground.points = las.points[las.classification == 2]

In [10]:
ground.write("data/ground.las")

In [11]:
ground_point_data = np.stack([ground.X, ground.Y, ground.Z], axis=0).transpose((1, 0))
ground_point_data

array([[ 65948887, 437130910,     56975],
       [ 65948947, 437130938,     56985],
       [ 65949008, 437130966,     56995],
       ...,
       [ 65953328, 437126017,     61060],
       [ 65953308, 437125997,     61060],
       [ 65953341, 437125868,     61153]], dtype=int32)

# 3D Point Cloud Visualization


In [ ]:
geom = o3d.geometry.PointCloud()
geom.points = o3d.utility.Vector3dVector(point_data)
o3d.visualization.draw_geometries([geom])